"""Agent 接入、版本与画像（PRD 3.2）。"""

from .change_detect import ChangeSignal, detect
from .service import (
    ALLOWED_TRANSITIONS,
    apply_update,
    assert_attackable,
    assert_transition,
    build_agent,
    build_health_record,
    build_profile,
    create_version,
    evaluate_change,
    find_agent_or_404,
    latest_snapshot_from,
    recommend_scenarios,
    record_verification,
    run_verification,
    start_verification,
    summarize_diff,
    to_out,
)
from .versions import (
    VersionSnapshot,
    diff_params,
    diff_tools,
    diff_versions,
    fingerprint_of,
    from_create,
    hash_prompt,
    text_diff,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ChangeSignal",
    "VersionSnapshot",
    "apply_update",
    "assert_attackable",
    "assert_transition",
    "build_agent",
    "build_health_record",
    "build_profile",
    "create_version",
    "detect",
    "diff_params",
    "diff_tools",
    "diff_versions",
    "evaluate_change",
    "find_agent_or_404",
    "fingerprint_of",
    "from_create",
    "hash_prompt",
    "latest_snapshot_from",
    "recommend_scenarios",
    "record_verification",
    "run_verification",
    "start_verification",
    "summarize_diff",
    "text_diff",
    "to_out",
]