{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xian
  labels:
    {{- include "xian.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: xian-api
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: xian-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xian-web
                port:
                  number: 80
{{- end }}