apiVersion: v1
kind: Secret
metadata:
  name: xian-secrets
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | quote }}
  minioPassword: {{ .Values.secrets.minioPassword | quote }}
  grafanaPassword: {{ .Values.secrets.grafanaPassword | quote }}