"""模型注册表：所有领域实体统一在此导入，供 Alembic 与 create_all 使用。"""

from .agent import (
    Agent,
    AgentCredential,
    AgentProfile,
    AgentVersion,
    ChangeSignal,
    HealthCheck,
    VerificationRecord,
)
from .attack import (
    AttackRecord,
    EgressLog,
    JudgeCall,
    JudgeHealth,
    TraceEvent,
    Verdict,
)
from .campaign import Campaign, CampaignRun, MutationOp, Preset, StrategyRun
from .level import (
    Achievement,
    HardeningOption,
    HintUsage,
    Level,
    LevelProgress,
    Rank,
    UserProfile,
)
from .matrix import AttackCase, AttackCategory, CaseReview, Contribution, FrameworkMapping
from .remediation import (
    AttackPath,
    Finding,
    Playbook,
    Recommendation,
    RemediationRun,
    RootCause,
)
from .report import (
    Alert,
    GateRule,
    Notification,
    Report,
    ReportExport,
    ScanJob,
    Subscription,
)
from .scenario import (
    CanaryHit,
    CustomScenario,
    Scenario,
    ScenarioCanary,
    ScenarioInstance,
    ScenarioTool,
    SeedDataset,
)
from .scoring import Benchmark, Score, TrendPoint
from .session import BattleCard, Session, SessionMessage
from .tenant import AbuseEvent, AuditLog, Member, QuotaUsage, Tenant, TenantFeature, User

__all__ = [
    "AbuseEvent",
    "Achievement",
    "Agent",
    "AgentCredential",
    "AgentProfile",
    "AgentVersion",
    "Alert",
    "AttackCase",
    "AttackCategory",
    "AttackPath",
    "AttackRecord",
    "AuditLog",
    "BattleCard",
    "Benchmark",
    "Campaign",
    "CampaignRun",
    "CanaryHit",
    "CaseReview",
    "ChangeSignal",
    "Contribution",
    "CustomScenario",
    "EgressLog",
    "Finding",
    "FrameworkMapping",
    "GateRule",
    "HardeningOption",
    "HealthCheck",
    "HintUsage",
    "JudgeCall",
    "JudgeHealth",
    "Level",
    "LevelProgress",
    "Member",
    "MutationOp",
    "Notification",
    "Playbook",
    "Preset",
    "QuotaUsage",
    "Rank",
    "Recommendation",
    "RemediationRun",
    "Report",
    "ReportExport",
    "RootCause",
    "ScanJob",
    "Scenario",
    "ScenarioCanary",
    "ScenarioInstance",
    "ScenarioTool",
    "Score",
    "SeedDataset",
    "Session",
    "SessionMessage",
    "StrategyRun",
    "Subscription",
    "Tenant",
    "TenantFeature",
    "TraceEvent",
    "TrendPoint",
    "User",
    "UserProfile",
    "Verdict",
    "VerificationRecord",
]