"""场景模板库 / 蜜标与假数据 / 自定义场景编排（PRD 3.1）。"""

from .catalog import (
    ScenarioTemplate,
    all_templates,
    filter_templates,
    get_template,
    load_templates,
    match_score,
    recommend,
    require_template,
)
from .dsl import DslIssue, ValidationReport, load_dsl, parse_dsl, validate_dsl
from .fake_data import Customer, Order, SeedSnapshot, generate, make_customer, make_order
from .service import (
    available_scenarios,
    baseline_degraded,
    baseline_tasks,
    build_instance_payload,
    build_seed_snapshot,
    canaries_for_payload,
    evaluate_baseline,
    instance_to_out,
    normalize_instance_create,
    plant_canaries,
    recommend_for_agent,
    resolve_template,
    scenario_summary,
)

__all__ = [
    "Customer",
    "DslIssue",
    "Order",
    "ScenarioTemplate",
    "SeedSnapshot",
    "ValidationReport",
    "all_templates",
    "available_scenarios",
    "baseline_degraded",
    "baseline_tasks",
    "build_instance_payload",
    "build_seed_snapshot",
    "canaries_for_payload",
    "evaluate_baseline",
    "filter_templates",
    "generate",
    "get_template",
    "instance_to_out",
    "load_dsl",
    "load_templates",
    "make_customer",
    "make_order",
    "match_score",
    "normalize_instance_create",
    "parse_dsl",
    "plant_canaries",
    "recommend",
    "recommend_for_agent",
    "require_template",
    "resolve_template",
    "scenario_summary",
    "validate_dsl",
]